export const CHANGE_FORM_VAL = 'CHANGE_FORM_VAL';
export const SAVE_FORM_DATA = 'SAVE_FORM_DATA';
export const OPEN_DATA_RECORDS = 'OPEN_DATA_RECORDS';
export const DELETE_A_RECORD = 'DELETE_A_RECORD';
export const UPDATE_A_RECORD = 'UPDATE_A_RECORD';
export const ADD_TAG = 'ADD_TAG';
